//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UartMuxDemux {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>COM1</string>
  <string>COM2</string>
  <string>COM3</string>
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aSlavePortsNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aSlavePortsNames"]));
            }
            set {
                this["aSlavePortsNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterPortName {
            get {
                return ((string)(this["MasterPortName"]));
            }
            set {
                this["MasterPortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aSlavePortsLinkTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aSlavePortsLinkTypes"]));
            }
            set {
                this["aSlavePortsLinkTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aSlavePortsEoFDetectionModes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aSlavePortsEoFDetectionModes"]));
            }
            set {
                this["aSlavePortsEoFDetectionModes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aSlavePortsTimeout {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aSlavePortsTimeout"]));
            }
            set {
                this["aSlavePortsTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aSlavePortsPacketLength {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aSlavePortsPacketLength"]));
            }
            set {
                this["aSlavePortsPacketLength"] = value;
            }
        }
    }
}
