//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UartMuxDemux {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>COM1</string>
  <string>COM2</string>
  <string>COM3</string>
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aDemuxPortsNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aDemuxPortsNames"]));
            }
            set {
                this["aDemuxPortsNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MuxPortName {
            get {
                return ((string)(this["MuxPortName"]));
            }
            set {
                this["MuxPortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
  <string>ASCII</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aDemuxPortsLinkTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aDemuxPortsLinkTypes"]));
            }
            set {
                this["aDemuxPortsLinkTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
  <string>Unknown</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aDemuxPortsEoFDetectionModes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aDemuxPortsEoFDetectionModes"]));
            }
            set {
                this["aDemuxPortsEoFDetectionModes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aDemuxPortsTimeout {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aDemuxPortsTimeout"]));
            }
            set {
                this["aDemuxPortsTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aDemuxPortsPacketLength {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aDemuxPortsPacketLength"]));
            }
            set {
                this["aDemuxPortsPacketLength"] = value;
            }
        }
    }
}
