//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UartMuxDemux.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>UNKNOWN_EV</string>\r\n  <string>RESET</string>\r\n  <string>EBUS_RESET</strin" +
            "g>\r\n  <string>COM_START</string>\r\n  <string>COM_EV_RESUME</string>\r\n  <string>NE" +
            "W_LINE</string>\r\n  <string>COM_EVENT</string>\r\n  <string>WRITE_MEM</string>\r\n  <" +
            "string>READ_MEM</string>\r\n  <string>FLASH_ACCESS_FROM_IT</string>\r\n  <string>EBU" +
            "S_UPDATE</string>\r\n  <string />\r\n  <string />\r\n  <string>EOF</string>\r\n  <string" +
            " />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r" +
            "\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string" +
            " />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r" +
            "\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string" +
            " />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r" +
            "\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string" +
            " />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r" +
            "\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string" +
            " />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string>TRA" +
            "CE_START_BYTE</string>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n" +
            "  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string " +
            "/>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string>TRACE_SPECIAL_BYTE</stri" +
            "ng>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aMessageConversion {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aMessageConversion"]));
            }
            set {
                this["aMessageConversion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int nbOfDemuxPorts {
            get {
                return ((int)(this["nbOfDemuxPorts"]));
            }
            set {
                this["nbOfDemuxPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort muxPort {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["muxPort"]));
            }
            set {
                this["muxPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort1 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort1"]));
            }
            set {
                this["demuxPort1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort2 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort2"]));
            }
            set {
                this["demuxPort2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort3 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort3"]));
            }
            set {
                this["demuxPort3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort4 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort4"]));
            }
            set {
                this["demuxPort4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort5 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort5"]));
            }
            set {
                this["demuxPort5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort6 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort6"]));
            }
            set {
                this["demuxPort6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort7 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort7"]));
            }
            set {
                this["demuxPort7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort8 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort8"]));
            }
            set {
                this["demuxPort8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort9 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort9"]));
            }
            set {
                this["demuxPort9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort10 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort10"]));
            }
            set {
                this["demuxPort10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort11 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort11"]));
            }
            set {
                this["demuxPort11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort12 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort12"]));
            }
            set {
                this["demuxPort12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort13 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort13"]));
            }
            set {
                this["demuxPort13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort14 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort14"]));
            }
            set {
                this["demuxPort14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort15 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort15"]));
            }
            set {
                this["demuxPort15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.IO.Ports.SerialPort demuxPort16 {
            get {
                return ((global::System.IO.Ports.SerialPort)(this["demuxPort16"]));
            }
            set {
                this["demuxPort16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType1 {
            get {
                return ((string)(this["linkType1"]));
            }
            set {
                this["linkType1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType2 {
            get {
                return ((string)(this["linkType2"]));
            }
            set {
                this["linkType2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType3 {
            get {
                return ((string)(this["linkType3"]));
            }
            set {
                this["linkType3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType4 {
            get {
                return ((string)(this["linkType4"]));
            }
            set {
                this["linkType4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType5 {
            get {
                return ((string)(this["linkType5"]));
            }
            set {
                this["linkType5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType6 {
            get {
                return ((string)(this["linkType6"]));
            }
            set {
                this["linkType6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType7 {
            get {
                return ((string)(this["linkType7"]));
            }
            set {
                this["linkType7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType8 {
            get {
                return ((string)(this["linkType8"]));
            }
            set {
                this["linkType8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType9 {
            get {
                return ((string)(this["linkType9"]));
            }
            set {
                this["linkType9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType10 {
            get {
                return ((string)(this["linkType10"]));
            }
            set {
                this["linkType10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType11 {
            get {
                return ((string)(this["linkType11"]));
            }
            set {
                this["linkType11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType12 {
            get {
                return ((string)(this["linkType12"]));
            }
            set {
                this["linkType12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType13 {
            get {
                return ((string)(this["linkType13"]));
            }
            set {
                this["linkType13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkType14 {
            get {
                return ((string)(this["linkType14"]));
            }
            set {
                this["linkType14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string linkType15 {
            get {
                return ((string)(this["linkType15"]));
            }
            set {
                this["linkType15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string linkType16 {
            get {
                return ((string)(this["linkType16"]));
            }
            set {
                this["linkType16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize1 {
            get {
                return ((uint)(this["frameSize1"]));
            }
            set {
                this["frameSize1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize2 {
            get {
                return ((uint)(this["frameSize2"]));
            }
            set {
                this["frameSize2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize3 {
            get {
                return ((uint)(this["frameSize3"]));
            }
            set {
                this["frameSize3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize4 {
            get {
                return ((uint)(this["frameSize4"]));
            }
            set {
                this["frameSize4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize5 {
            get {
                return ((uint)(this["frameSize5"]));
            }
            set {
                this["frameSize5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize6 {
            get {
                return ((uint)(this["frameSize6"]));
            }
            set {
                this["frameSize6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize7 {
            get {
                return ((uint)(this["frameSize7"]));
            }
            set {
                this["frameSize7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize8 {
            get {
                return ((uint)(this["frameSize8"]));
            }
            set {
                this["frameSize8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize9 {
            get {
                return ((uint)(this["frameSize9"]));
            }
            set {
                this["frameSize9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize10 {
            get {
                return ((uint)(this["frameSize10"]));
            }
            set {
                this["frameSize10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize11 {
            get {
                return ((uint)(this["frameSize11"]));
            }
            set {
                this["frameSize11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize12 {
            get {
                return ((uint)(this["frameSize12"]));
            }
            set {
                this["frameSize12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize13 {
            get {
                return ((uint)(this["frameSize13"]));
            }
            set {
                this["frameSize13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize14 {
            get {
                return ((uint)(this["frameSize14"]));
            }
            set {
                this["frameSize14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize15 {
            get {
                return ((uint)(this["frameSize15"]));
            }
            set {
                this["frameSize15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint frameSize16 {
            get {
                return ((uint)(this["frameSize16"]));
            }
            set {
                this["frameSize16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte1 {
            get {
                return ((byte)(this["eoFByte1"]));
            }
            set {
                this["eoFByte1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte2 {
            get {
                return ((byte)(this["eoFByte2"]));
            }
            set {
                this["eoFByte2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte3 {
            get {
                return ((byte)(this["eoFByte3"]));
            }
            set {
                this["eoFByte3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte4 {
            get {
                return ((byte)(this["eoFByte4"]));
            }
            set {
                this["eoFByte4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte5 {
            get {
                return ((byte)(this["eoFByte5"]));
            }
            set {
                this["eoFByte5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte6 {
            get {
                return ((byte)(this["eoFByte6"]));
            }
            set {
                this["eoFByte6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte7 {
            get {
                return ((byte)(this["eoFByte7"]));
            }
            set {
                this["eoFByte7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte8 {
            get {
                return ((byte)(this["eoFByte8"]));
            }
            set {
                this["eoFByte8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte9 {
            get {
                return ((byte)(this["eoFByte9"]));
            }
            set {
                this["eoFByte9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte10 {
            get {
                return ((byte)(this["eoFByte10"]));
            }
            set {
                this["eoFByte10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte11 {
            get {
                return ((byte)(this["eoFByte11"]));
            }
            set {
                this["eoFByte11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte12 {
            get {
                return ((byte)(this["eoFByte12"]));
            }
            set {
                this["eoFByte12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte13 {
            get {
                return ((byte)(this["eoFByte13"]));
            }
            set {
                this["eoFByte13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte14 {
            get {
                return ((byte)(this["eoFByte14"]));
            }
            set {
                this["eoFByte14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte15 {
            get {
                return ((byte)(this["eoFByte15"]));
            }
            set {
                this["eoFByte15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte eoFByte16 {
            get {
                return ((byte)(this["eoFByte16"]));
            }
            set {
                this["eoFByte16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter1 {
            get {
                return ((string)(this["frameDelimiter1"]));
            }
            set {
                this["frameDelimiter1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter2 {
            get {
                return ((string)(this["frameDelimiter2"]));
            }
            set {
                this["frameDelimiter2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter3 {
            get {
                return ((string)(this["frameDelimiter3"]));
            }
            set {
                this["frameDelimiter3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter4 {
            get {
                return ((string)(this["frameDelimiter4"]));
            }
            set {
                this["frameDelimiter4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter5 {
            get {
                return ((string)(this["frameDelimiter5"]));
            }
            set {
                this["frameDelimiter5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter6 {
            get {
                return ((string)(this["frameDelimiter6"]));
            }
            set {
                this["frameDelimiter6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter7 {
            get {
                return ((string)(this["frameDelimiter7"]));
            }
            set {
                this["frameDelimiter7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter8 {
            get {
                return ((string)(this["frameDelimiter8"]));
            }
            set {
                this["frameDelimiter8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter9 {
            get {
                return ((string)(this["frameDelimiter9"]));
            }
            set {
                this["frameDelimiter9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter10 {
            get {
                return ((string)(this["frameDelimiter10"]));
            }
            set {
                this["frameDelimiter10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter11 {
            get {
                return ((string)(this["frameDelimiter11"]));
            }
            set {
                this["frameDelimiter11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter12 {
            get {
                return ((string)(this["frameDelimiter12"]));
            }
            set {
                this["frameDelimiter12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter13 {
            get {
                return ((string)(this["frameDelimiter13"]));
            }
            set {
                this["frameDelimiter13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter14 {
            get {
                return ((string)(this["frameDelimiter14"]));
            }
            set {
                this["frameDelimiter14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter15 {
            get {
                return ((string)(this["frameDelimiter15"]));
            }
            set {
                this["frameDelimiter15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frameDelimiter16 {
            get {
                return ((string)(this["frameDelimiter16"]));
            }
            set {
                this["frameDelimiter16"] = value;
            }
        }
    }
}
