//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UartMuxDemux.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>UNKNOWN_EV</string>\r\n  <string>RESET</string>\r\n  <string>EBUS_RESET</strin" +
            "g>\r\n  <string>COM_START</string>\r\n  <string>COM_EV_RESUME</string>\r\n  <string>NE" +
            "W_LINE</string>\r\n  <string>COM_EVENT</string>\r\n  <string>WRITE_MEM</string>\r\n  <" +
            "string>READ_MEM</string>\r\n  <string>FLASH_ACCESS_FROM_IT</string>\r\n  <string>EBU" +
            "S_UPDATE</string>\r\n  <string />\r\n  <string />\r\n  <string>EOF</string>\r\n  <string" +
            " />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r" +
            "\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string" +
            " />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r" +
            "\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string" +
            " />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r" +
            "\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string" +
            " />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r" +
            "\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string" +
            " />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string>TRA" +
            "CE_START_BYTE</string>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n" +
            "  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string " +
            "/>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string>TRACE_SPECIAL_BYTE</stri" +
            "ng>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <st" +
            "ring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n " +
            " <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string /" +
            ">\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <stri" +
            "ng />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <" +
            "string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection aMessageConversion {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["aMessageConversion"]));
            }
            set {
                this["aMessageConversion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("208")]
        public byte startByte {
            get {
                return ((byte)(this["startByte"]));
            }
            set {
                this["startByte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public byte eofByte {
            get {
                return ((byte)(this["eofByte"]));
            }
            set {
                this["eofByte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("222")]
        public byte specialByte {
            get {
                return ((byte)(this["specialByte"]));
            }
            set {
                this["specialByte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int serialBaudrate {
            get {
                return ((int)(this["serialBaudrate"]));
            }
            set {
                this["serialBaudrate"] = value;
            }
        }
    }
}
